version: "3"

# services:
#   holadocker:
#     build: .
#     ports:
#       - 83:80

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  container-test:
    image: xhos1234/hola-docker
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=mos1234.tk,www.mos1234.tk
      - LETSENCRYPT_HOST=mos1234.tk,www.mos1234.tk
      - LETSENCRYPT_EMAIL=mos@mos1234.tk

volumes:
  certs:
  html:
  vhostd:
